apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "av.fullname" . }}-config
  labels:
    {{- include "av.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.backend.env.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.backend.env.LOG_LEVEL | quote }}
  ALLOWED_ORIGINS: {{ include "av.allowedOrigins" . | quote }}
